const fs=require('node:fs'), vm=require('node:vm'), assert=require('node:assert/strict');
const sandbox={};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('jevernetes/web/context.js','utf8')+';globalThis.helpers=LogContext',sandbox);
const h=sandbox.helpers;
const source={type:'kubernetes',context:'demo',namespace:'demo',pod:'api-one',container:'app',pod_uid:'one',restart_count:0};
const anchor={id:'selected',source,timestamp:'2026-09-20T12:00:00Z',text:'ERROR problem',importance:'important',line_start:20,line_end:20};
const before={...anchor,id:'before',timestamp:'2026-09-20T11:59:59Z',text:'INFO routine',importance:'routine',line_start:19,line_end:19};
const other={...anchor,id:'other',source:{...source,pod:'worker-one'},timestamp:'2026-09-20T12:00:01Z'};
const outside={...anchor,id:'outside',timestamp:'2026-09-20T12:10:00Z'};
assert.equal(h.nearby([anchor,before,other,outside],anchor,120).length,3);
assert.equal(h.nearby([anchor,before,other],anchor,120).filter(e=>h.matches(e,{pod:'api-one'})).length,2);
assert.equal(h.collected({events:[anchor],tail_events:[{...anchor,importance:'pending'}]})[0].importance,'important');
const fetched=[{...anchor,id:'fetched',context_only:true},{...before,id:'fetched-before'}];
const merged=h.withFetched([anchor,before,other],fetched,anchor);
assert.equal(merged.filter(e=>e.id==='selected').length,1);
assert.equal(merged.filter(e=>e.id==='other').length,1);
assert.equal(merged.length,3);
const file={...anchor,source:{type:'file',path:'app.log'},timestamp:null};
assert.equal(h.nearby([file,{...file,id:'far',line_start:1000,line_end:1000}],file,30).length,1);
assert.equal(h.sameInstance(source,{...source,restart_count:1}),false);
console.log('Context UI helpers: filtering, routine neighbors, file windows, instance separation and selected-event preservation passed');
